### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by glichtenstein** [maribuon/HattCI#2]
Hello, I am having problems installing HattCI and running the tutorial test I got a Segmentation Fault, any help would be appreciated, thank you very much!

glichtenstein@impam2:~/HattCI-master$ make
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o main.o main.c
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o paraRead.o paraRead.c
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o hmm.o hmm.c
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o viterbi.o viterbi.c
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o readFasta.o readFasta.c
gcc -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"'   -c -o calcResults.o calcResults.c
gcc  -o hattci.out -O3 -fopenmp -g -std=c99 -D DIR='"/home/glichtenstein/HattCI-master"' main.o paraRead.o hmm.o viterbi.o readFasta.o calcResults.o -lm

glichtenstein@impam2:~/HattCI-master$ cd ..

glichtenstein@impam2:~$ ./HattCI-master/hattci.out tutorial.fasta tutorial.out
Segmentation fault (core dumped)

**Comment by maribuon** [comment]
Hi LuxLapis,

I am sorry for the late reply. The problem is with the above is that the fasta file (tutorial.fasta) is not in the folder. Please try the following, from the folder /home/glichtenstein/

 ./HattCI-master/hattci.out ./HattCI-master/data/tutorial.fasta tuorial.out

You should get:
Mbases processed: 0.015136
Sequences read: 3
Sequences processed: 3
Hits: 9

What do you see?

Cheers,
Mariana

**Comment by glichtenstein** [comment]
I see this:

Mbases processed: 0.015136
Sequences read: 3
Sequences processed: 3
Hits: 9

**Comment by glichtenstein** [comment]
#update:

I was able to install it in the production server and give acces to all users to the hattci.out but it gave me error about:

> glichtenstein@impam2:/share/apps/HattCI-master$ ./hattci.out ./data/tutorial.fasta ~/results.txt
> Problems opening file est_ini.txt

So I did:

> glichtenstein@impam2:/share/apps/HattCI-master/parameters$ sudo chmod 777 *
> glichtenstein@impam2:/share/apps/HattCI-master/parameters$ ll
> total 36
> drwxrwxrwx 2 root root  4096 abr 21 12:54 ./
> drwxr-xr-x 6 root root  4096 jul 20 10:29 ../
> -rwxrwxrwx 1 root root 13266 abr 21 12:54 est_emi.txt*
> -rwxrwxrwx 1 root root   165 abr 21 12:54 est_ini.txt*
> -rwxrwxrwx 1 root root   219 abr 21 12:54 est_trans.txt*
> -rwxrwxrwx 1 root root  2557 abr 21 12:54 f.txt*

but still:
> glichtenstein@impam2:/share/apps/HattCI-master$ ./hattci.out ./data/tutorial.fasta ~/results.txt
> Problems opening file est_ini.txt

the workaround in this case was to:

> glichtenstein@impam2:/share/apps/HattCI-master$ sudo make clean
> glichtenstein@impam2:/share/apps/HattCI-master$ cd ..
> glichtenstein@impam2:/share/apps$ sudo chmod a+rwx HattCI-master/ -Rfv
> glichtenstein@impam2:/share/apps$ cd HattCI-master/
> glichtenstein@impam2:/share/apps/HattCI-master$ make
> glichtenstein@impam2:/share/apps/HattCI-master$ /share/apps/HattCI-master/hattci.out /share/apps/HattCI-master/data/tutorial.fasta /home/glichtenstein/results.txt
> Mbases processed: 0.015136
> Sequences read: 3
> Sequences processed: 3
> Hits: 9

and it now works for all users:

> mmasso@impam2:~/Desktop/HattCI$ hattci.out ~/Desktop/HattCI/CP012363.1.whole.fasta ~/Desktop/HattCI/CP012363.1.whole.hatci_results.out
> Mbases processed: 2.391994
> Sequences read: 1
> Sequences processed: 1
> Hits: 169
> 

Thank you very much Mariana! :)

**Comment by maribuon** [comment]
Great! :) I am very happy to hear it works! Please let me know if any problem arises again.
